himePhrases = [
    "Every attempt at making an argument you Fail. You try to make a map and Fail. You try doing anything and Failure is the only path you walk towards. You live a life devoid of any meaning. Stop trying to talk to me when you lack the mental fortitude to even say something tangible.",
    "'Grow up' says the man crying and asking to blame himself for being a complete fucking nutjob at placing circles in the editor. Thanks for proving my point once again retard.",
    "The 'Growing up' that this fellow is talking about isn't about me being more mature. What he's actually trying to tell me is 'if you dont accept my stance then you're immature!' Well to be honest with you, I don't want to 'grow up' then.",
    "You're sorry? You should be groveling on the ground begging for forgiveness you insolent rat. You and your fuckbuddy stompy racing each other to see who makes it further up the others asshole to nominate the shittiest maps known to osu!kind. You're all that is wrong with osu!.",
    "What sort of nonsense word vomit are you letting out with this?? If a map is nominated then the BN approves of it, In turn if the map is shit then the BN approves of shit. Maps being shit is not subjective.",
    "Do you just like making things up too? I'm not a therapist but maybe perhaps (A sign mayhaps.) of some sort of a degrading mental illness causing chronic memory loss (Could we perhaps call them memories?) might be causing you to forget you're a worm.",
    "It is evident that your attempts to construct a compelling argument have thus far been met with a profound lack of success, as evidenced by your repeated failures to present a cogent and persuasive case. Even when undertaking tasks as seemingly straightforward as creating a map, your efforts have been fraught with frustration and ineffectuality.",
    "Regrettably, it appears that your life has thus far been characterized by a distinct dearth of meaning or purpose, leaving you adrift in a sea of ennui and existential uncertainty. Given this pervasive sense of aimlessness, it may be advisable for you to refrain from engaging with me in any further intellectual discourse, as your current level of mental fortitude and capacity for reasoned dialogue seem woefully inadequate to the task.",
    "Rather than continuing to struggle in vain against these formidable intellectual hurdles, it might be more productive for you to undertake a period of intense self-reflection and self-improvement, focusing your energies on developing your cognitive capabilities and enhancing your overall intellectual prowess. In so doing, you may be able to transcend your current limitations and meaningfully contribute to the world of ideas in the future.",
    "This argument appears every time something like this happens and its fattest cope to ever grace osu!mapping. He's such a nice person bro, you're just being an asshole... So what? Just because hes nice hes exempt from ever being criticized by anyone? Grow the fuck up.",
    "You're a Turk. You know nothing of Egypt's pride nor ancestry. You Will Never be Egyptian. Go crawl back to the hole where you came out of you cockroach and get yourself an education first. and Don't you dare sully the name of Allah again.",
    "You're gay. Almost everyone that complains about Anime girls is gay. And I don't mean you can't not like Anime girls if you're straight, but straight guys don't complain about them like gay guys do. signaling them out like this is sure sign you're dealing with a homosexual."
    ]